apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secret
    namespace: keycloak
    labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: auth
type: Opaque
stringData:
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:t5wN8pw=,iv:HRCsi7J/gdyWkBvT1T1T4FojO0qc+hIPZ9ZrhLwgeMU=,tag:Hj10FkxRYYodXLz8zOfpNQ==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:++NcloaD3EGIAB0m,iv:JPEhfcMFqdAqlyJDAvOUrxy5RPhNKh1w11zRcuyHyh0=,tag:y8NRumVeRFDql7NlsCdggA==,type:str]
    KC_DB: ENC[AES256_GCM,data:+AsuuyStTiU=,iv:yKbBZxd3Rn8ElTJVLPaa81U5fdF5JkA3siFFpPuc4dY=,tag:0zput+Wh14H+mataNVPp0w==,type:str]
    KC_DB_URL: ENC[AES256_GCM,data:RyJBOdFJMw4dF4MBi5ObxDtsQC9sh81+7nxpL2KIrSL/VAxIhxDj1BV7nAmnOUauanXwqp2z0Cmj5SBmfEa/6S9Wng==,iv:rCMmrC3soE2fDbyq/B9rBsdBsiWH0ucFlwKz7zTV4nE=,tag:8Okr1/Ec8cgccrenLvnCRg==,type:str]
    KC_DB_USERNAME: ENC[AES256_GCM,data:FaFzYZCNNXw=,iv:584/I47iazIKpiZQ8fUl/WqwOk5+kPWdP2uA1KQYyWY=,tag:2QAaXZNPjtPo3NhaWjGDfg==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:NO1ZqW2qmUkcCzGvjySCXDPkgJ8+vNCaFN3NPg==,iv:hQSibncmPkjU8fHtViSzSGOu32+8LfYvVm7GiSB2AbU=,tag:Mixj8MXCqJNuFCR3R/OoBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxN3R0MTRZUDJiOFArUHp3
            UVpjT0NyZXF0QnpldmkxbFQ1U0xRVmI3M3dZCm9LRTRlR1FTUS9yTHRmTWFDaS9u
            RjhNcy9oR21BRVRzZ3h4WXEwQ1oyUFkKLS0tIHA4clg5SFcweDZMYzR5UG5obnEr
            Mnl6S09ueVZETWw1UzNEY0k3bWlRaUkK2p6BMT0jW49VCvyY2NTWra6xRcjSWv8H
            0z4GyilF+0ZTrb9kwOEGgLUdeWTOUpTAvxOih/svC7YA/dc5tuBHXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T13:34:40Z"
    mac: ENC[AES256_GCM,data:C8Pjoc1iZfqny4LmPhBvFFKD23f+Z4cP1BKkmxQqZmpoJKDCJExj6hDOPZYV3BP1wqyhWQYbSTDS0CIfRAlajFh5SShD7EQcn2P4AKDV5wD/QSlrPL4P6o/kC3S1JNlE7ji0i05M2MmO+aZwQhin9x8NSLnWmmKSsHen1kkqf/U=,iv:fwNpAoiXP3qKAKHw1azAirlLY41//3lqLFyR65EfcPE=,tag:AaRaJrxAepXnmsNh21Zc8Q==,type:str]
    version: 3.13.3
