# GITHUB_TOKEN: a personal access token whose only permission is Gists
# (read/write). It can touch nothing else on the account.
# GIST_ID: the id of the gist (gh gist create); the job only updates it.
apiVersion: v1
kind: Secret
metadata:
    name: status-badges
    namespace: monitoring
type: Opaque
stringData:
    GIST_ID: ENC[AES256_GCM,data:C9freUAM+EWPWJAaHApDOmF8tU2+NqPf+n7FCSyupx4=,iv:TjiQwISHZbE0VbuZFzStr4vnctxaDLGYk7lRHwLzPo4=,tag:Q4flAlrUXa+rk20XvXejyQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:nCTa69Rt148xMp+XkfX8q6RgLz0tFYgjhc5PhyJXFvBh32RqgUdVUxuTbdY4VoQPOSqJ85p6MCwJ14aTYkyxQ1mbNJvXR2nuJvydRB4ltNwZLEYbxzvCRa1zHYYU,iv:Wz7DDZ8k0+Or3kPdgh31FaK6Zcs/iB3Upyct2JmX1Yc=,tag:E7b1Uo+Nxgbm+MuAY/g4ew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S0RGWS9Va2wyWndmcEdP
            OVhLbi9pZmFsN0lsdFFlc0VKT1RaWlFxY0JZClhGT1I0OEFsNlU4U1lRTXlBeTVS
            YzBmbzhmZW5UdWx2UFJVaWdZdFB6a3cKLS0tIDhTRFozMG01elJ5MW9uajQ5YmJn
            a3dxdGRpT1hFQ2I4N1VFLzRyTFBMSmcKMpr/pgiWBg8OK2FgVrtn2qlFGRmJNhgq
            jHKpAIOf+8vdWabE/kHDTna8sqpDB4yc9YwCcd0bCuNe1cn7EV9VAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T11:18:32Z"
    mac: ENC[AES256_GCM,data:NBRyajWI4rnrWNQNlFq/MQ/RyKBQwGIenYpQ0zOXA13P+77UVRlaXvWzT9Y+Uk7xErDqRK+olNeJtWhW+9DtUpxVuyFDTKpVV8iQe1548GLBnWCSKY/YbJrJs5SG7l1fsJydPdtSHrAVCpHLLC27pJugZUPuBZ+RCOZZ29EKLe8=,iv:SEwfrzHp+tnLILR64inih8akwm4lhPhDL1A/eH27WyY=,tag:5ylhHtji4TtnaFrsDeekmQ==,type:str]
    version: 3.13.3
